name: vector
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.7
  - conda:
    - root # install if needed (huge package)
  - pip
  - pip:
    - pandas==2.2.0
    - scikit-learn==1.4.0
    - numpy==1.26.0
    - uproot==5.2.1
    - awkward==2.5.2
    - matplotlib==3.8.2
    - seaborn==0.13.1
    - statsmodels==0.14.1
    - tqdm==4.64.1
    - scipy==1.12.0
    - shap==0.45.1
    - pickleshare==0.7.5
    - plotly==5.10.0
    - jupyter==1.0.0
    - jupyter-client==7.3.1
    - jupyter-console==6.4.3
    - jupyter-core==4.10.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.0
    - matplotlib-inline==0.1.3
    - notebook==6.4.11
    - iminuit==2.24.0
    - pytest==7.1.3
    - imbalanced-learn==0.12.2